# XcodeGen spec — generates WinkorNext.xcodeproj at build time (no Xcode required locally)
name: WinkorNext
options:
  bundleIdPrefix: com.winkornext
  deploymentTarget:
    iOS: "26.2"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

targets:
  WinkorNext:
    type: application
    platform: iOS
    sources:
      - WinkorNext
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: WinkorNext/WinkorNext.entitlements
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: WinkorNext/Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        MARKETING_VERSION: "1.0.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.winkornext.app
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies: []
    preBuildScripts: []
    postCompileScripts: []

schemes:
  WinkorNext:
    build:
      targets:
        WinkorNext: all
    run:
      config: Debug
    archive:
      config: Release
